import { describe, expect, it } from "vitest";
import fs from "node:fs";
import path from "node:path";

import airports from "./airports.json";

// The shipped reference data is generated by python/create_airports_json.py and
// deliberately carries only the fields the app reads. This guards both ends of
// that trade: regenerating must not drop a field something depends on, and must
// not quietly reintroduce the unused ones that cost ~430 KB.
const EXPECTED_KEYS = [
  "iata",
  "airport_name",
  "city",
  "country",
  "lat",
  "lon",
  "iso_country",
];

describe("airports.json", () => {
  it("carries exactly the fields the app reads", () => {
    const keys = new Set<string>();
    for (const airport of airports as Record<string, unknown>[]) {
      Object.keys(airport).forEach((k) => keys.add(k));
    }
    expect([...keys].sort()).toEqual([...EXPECTED_KEYS].sort());
  });

  it("has a usable record for a well-known airport", () => {
    const syd = (airports as Record<string, unknown>[]).find(
      (a) => a.iata === "SYD",
    );
    expect(syd).toBeDefined();
    expect(syd?.city).toBeTruthy();
    expect(typeof syd?.lat).toBe("number");
    expect(typeof syd?.lon).toBe("number");
    expect(syd?.iso_country).toBe("AU");
  });

  it("stays pretty-printed in git, since the build minifies it", () => {
    // Keeps the diff of a 4500-record data file reviewable.
    const raw = fs.readFileSync(
      path.resolve(process.cwd(), "src/assets/airports.json"),
      "utf8",
    );
    expect(raw.startsWith("[\n  {")).toBe(true);
  });
});
