name: CI/CD

on:
  push:
    branches: [development]
  pull_request:
    branches: [development]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm ci
      - name: Run unit tests
        run: npm run vitest
      - name: Build
        run: npm run build
  e2e:
    name: Cypress E2E
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - name: Run Cypress
        uses: cypress-io/github-action@v6
        with:
          install: true
          build: npm run build
          start: npm run preview -- --port 5173
          wait-on: 'http://localhost:5173'
        env:
          CI: true
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
          CY_TEST_EMAIL: ${{ secrets.CY_TEST_EMAIL }}
          CY_TEST_PASSWORD: ${{ secrets.CY_TEST_PASSWORD }}
          CY_WRONG_EMAIL: ${{ secrets.CY_WRONG_EMAIL }}
          CY_WRONG_PASSWORD: ${{ secrets.CY_WRONG_PASSWORD }}
      - name: Upload Cypress Screenshots
        uses: actions/upload-artifact@v4
        if: always() # Uploads artifacts even if previous steps fail
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          retention-days: 7 # Optional: define how long to keep the artifacts

          # Add other secrets as needed

#  # Optional: auto-create PR to main if tests pass
#  create-pr:
#    needs: test
#    runs-on: ubuntu-latest
#    if: success()
#    steps:
#      - uses: actions/checkout@v4
#      - name: Create Pull Request to main
#        uses: peter-evans/create-pull-request@v7
#        with:
#          commit-message: "Automated PR after test success"
#          base: main # The branch to create the PR against
#          branch: development # The branch to create the PR from
#          title: 'Promote development to main'
#          body: 'Automated PR to promote development to main after tests pass.'
